// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IHeroiconsOutline:checkCircle': typeof import('virtual:vite-icons/heroicons-outline/check-circle')['default']
    'MyFoo.ce': typeof import('./lib/components/MyFoo.ce.vue')['default']
    NestedComponent: typeof import('./lib/components/NestedComponent.vue')['default']
  }
}

export { }
